=begin
#BVNK API Endpoints

#The BVNK API is designed to facilitate seamless and secure transactions including payments, channels, and digital wallet transactions.

The version of the OpenAPI document: 1.0.1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0

=end

require 'date'
require 'time'

module OpenapiClient
  class MerchantChannelDto
    # The UUID of the channel.
    attr_accessor :id

    # The date and time, encoded into UNIX epoch timestamps.
    attr_accessor :date_created

    # The date and time, encoded into UNIX epoch timestamps.
    attr_accessor :last_updated

    # The merchant ID linked to the channel.
    attr_accessor :merchant_id

    # The wallet currency of the channel.
    attr_accessor :wallet_currency

    # The display currency of the channel.
    attr_accessor :display_currency

    # The payed currency of the channel.
    attr_accessor :pay_currency

    # The address of the channel
    attr_accessor :address

    # The tag for payments
    attr_accessor :tag

    # The protocol of the channel.
    attr_accessor :protocol

    # The custom reference for the channel payment.
    attr_accessor :reference

    # The status of the channel.
    attr_accessor :status

    # The UUID of the channel.
    attr_accessor :uuid

    # The redirect URL to the channel payment page.
    attr_accessor :redirect_url

    # The URI of the address for QR code
    attr_accessor :uri

    attr_accessor :alternatives

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'date_created' => :'dateCreated',
        :'last_updated' => :'lastUpdated',
        :'merchant_id' => :'merchantId',
        :'wallet_currency' => :'walletCurrency',
        :'display_currency' => :'displayCurrency',
        :'pay_currency' => :'payCurrency',
        :'address' => :'address',
        :'tag' => :'tag',
        :'protocol' => :'protocol',
        :'reference' => :'reference',
        :'status' => :'status',
        :'uuid' => :'uuid',
        :'redirect_url' => :'redirectUrl',
        :'uri' => :'uri',
        :'alternatives' => :'alternatives'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'Integer',
        :'date_created' => :'Integer',
        :'last_updated' => :'Integer',
        :'merchant_id' => :'String',
        :'wallet_currency' => :'String',
        :'display_currency' => :'String',
        :'pay_currency' => :'String',
        :'address' => :'String',
        :'tag' => :'String',
        :'protocol' => :'String',
        :'reference' => :'String',
        :'status' => :'String',
        :'uuid' => :'String',
        :'redirect_url' => :'String',
        :'uri' => :'String',
        :'alternatives' => :'Array<AlternativeAddressDto>'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `OpenapiClient::MerchantChannelDto` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `OpenapiClient::MerchantChannelDto`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      else
        self.id = 0
      end

      if attributes.key?(:'date_created')
        self.date_created = attributes[:'date_created']
      else
        self.date_created = 0
      end

      if attributes.key?(:'last_updated')
        self.last_updated = attributes[:'last_updated']
      else
        self.last_updated = 0
      end

      if attributes.key?(:'merchant_id')
        self.merchant_id = attributes[:'merchant_id']
      end

      if attributes.key?(:'wallet_currency')
        self.wallet_currency = attributes[:'wallet_currency']
      end

      if attributes.key?(:'display_currency')
        self.display_currency = attributes[:'display_currency']
      end

      if attributes.key?(:'pay_currency')
        self.pay_currency = attributes[:'pay_currency']
      end

      if attributes.key?(:'address')
        self.address = attributes[:'address']
      end

      if attributes.key?(:'tag')
        self.tag = attributes[:'tag']
      end

      if attributes.key?(:'protocol')
        self.protocol = attributes[:'protocol']
      end

      if attributes.key?(:'reference')
        self.reference = attributes[:'reference']
      end

      if attributes.key?(:'status')
        self.status = attributes[:'status']
      end

      if attributes.key?(:'uuid')
        self.uuid = attributes[:'uuid']
      end

      if attributes.key?(:'redirect_url')
        self.redirect_url = attributes[:'redirect_url']
      end

      if attributes.key?(:'uri')
        self.uri = attributes[:'uri']
      end

      if attributes.key?(:'alternatives')
        if (value = attributes[:'alternatives']).is_a?(Array)
          self.alternatives = value
        end
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      status_validator = EnumAttributeValidator.new('String', ["OPEN", "CLOSED"])
      return false unless status_validator.valid?(@status)
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] status Object to be assigned
    def status=(status)
      validator = EnumAttributeValidator.new('String', ["OPEN", "CLOSED"])
      unless validator.valid?(status)
        fail ArgumentError, "invalid value for \"status\", must be one of #{validator.allowable_values}."
      end
      @status = status
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          date_created == o.date_created &&
          last_updated == o.last_updated &&
          merchant_id == o.merchant_id &&
          wallet_currency == o.wallet_currency &&
          display_currency == o.display_currency &&
          pay_currency == o.pay_currency &&
          address == o.address &&
          tag == o.tag &&
          protocol == o.protocol &&
          reference == o.reference &&
          status == o.status &&
          uuid == o.uuid &&
          redirect_url == o.redirect_url &&
          uri == o.uri &&
          alternatives == o.alternatives
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, date_created, last_updated, merchant_id, wallet_currency, display_currency, pay_currency, address, tag, protocol, reference, status, uuid, redirect_url, uri, alternatives].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      self.class.openapi_types.each_pair do |key, type|
        if attributes[self.class.attribute_map[key]].nil? && self.class.openapi_nullable.include?(key)
          self.send("#{key}=", nil)
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = OpenapiClient.const_get(type)
        klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
