=begin
#BVNK API Endpoints

#The BVNK API is designed to facilitate seamless and secure transactions including payments, channels, and digital wallet transactions.

The version of the OpenAPI document: 1.0.1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0

=end

require 'date'
require 'time'

module OpenapiClient
  class PaymentStatusDto
    PENDING = "PENDING".freeze
    PROCESSING = "PROCESSING".freeze
    CANCELLED = "CANCELLED".freeze
    COMPLETE = "COMPLETE".freeze
    UNDERPAID = "UNDERPAID".freeze
    OVERPAID = "OVERPAID".freeze
    EXPIRED = "EXPIRED".freeze

    def self.all_vars
      @all_vars ||= [PENDING, PROCESSING, CANCELLED, COMPLETE, UNDERPAID, OVERPAID, EXPIRED].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if PaymentStatusDto.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #PaymentStatusDto"
    end
  end
end
