=begin
#BVNK API Endpoints

#The BVNK API is designed to facilitate seamless and secure transactions including payments, channels, and digital wallet transactions.

The version of the OpenAPI document: 1.0.1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0

=end

require 'date'
require 'time'

module OpenapiClient
  # Contains all the information about a summary payment object returned.
  class SummaryPaymentDto
    # The unique identifier for the merchant payment.
    attr_accessor :uuid

    # The display name for the merchant payment.
    attr_accessor :merchant_display_name

    # The Merchant ID. You can find it on the Merchant Details page in your account.
    attr_accessor :merchant_id

    # The date and time, encoded into UNIX epoch timestamps.
    attr_accessor :date_created

    # The date and time, encoded into UNIX epoch timestamps
    attr_accessor :expiry_date

    # The date and time, encoded into UNIX epoch timestamps
    attr_accessor :quote_expiry_date

    # The date and time, encoded into UNIX epoch timestamps
    attr_accessor :acceptance_expiry_date

    attr_accessor :quote_status

    # The custom payment reference ID to tie the payment to your customer.
    attr_accessor :reference

    attr_accessor :type

    # The payment sub type
    attr_accessor :sub_type

    attr_accessor :status

    attr_accessor :display_currency

    attr_accessor :wallet_currency

    attr_accessor :paid_currency

    attr_accessor :fee_currency

    attr_accessor :display_rate

    attr_accessor :exchange_rate

    attr_accessor :address

    # The URL that the customer will be redirected to if they click 'Back to Merchant' button on the payment web page.
    attr_accessor :return_url

    # The URL to the payment page that you redirect your customers to.
    attr_accessor :redirect_url

    attr_accessor :transactions

    # The payment this object is a refund of. This should reference the pay in that this refund was created for.
    attr_accessor :refund

    # Refunds that have been requested for this payment. This should reference the refund payout for this pay in.
    attr_accessor :refunds

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'uuid' => :'uuid',
        :'merchant_display_name' => :'merchantDisplayName',
        :'merchant_id' => :'merchantId',
        :'date_created' => :'dateCreated',
        :'expiry_date' => :'expiryDate',
        :'quote_expiry_date' => :'quoteExpiryDate',
        :'acceptance_expiry_date' => :'acceptanceExpiryDate',
        :'quote_status' => :'quoteStatus',
        :'reference' => :'reference',
        :'type' => :'type',
        :'sub_type' => :'subType',
        :'status' => :'status',
        :'display_currency' => :'displayCurrency',
        :'wallet_currency' => :'walletCurrency',
        :'paid_currency' => :'paidCurrency',
        :'fee_currency' => :'feeCurrency',
        :'display_rate' => :'displayRate',
        :'exchange_rate' => :'exchangeRate',
        :'address' => :'address',
        :'return_url' => :'returnUrl',
        :'redirect_url' => :'redirectUrl',
        :'transactions' => :'transactions',
        :'refund' => :'refund',
        :'refunds' => :'refunds'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'uuid' => :'String',
        :'merchant_display_name' => :'String',
        :'merchant_id' => :'String',
        :'date_created' => :'Integer',
        :'expiry_date' => :'Integer',
        :'quote_expiry_date' => :'Integer',
        :'acceptance_expiry_date' => :'Integer',
        :'quote_status' => :'String',
        :'reference' => :'String',
        :'type' => :'DirectionDto',
        :'sub_type' => :'String',
        :'status' => :'PaymentStatusDto',
        :'display_currency' => :'PayAmountsDto',
        :'wallet_currency' => :'PayAmountsDto',
        :'paid_currency' => :'PayAmountsDto',
        :'fee_currency' => :'PayAmountsDto',
        :'display_rate' => :'ExchangeRateDto',
        :'exchange_rate' => :'ExchangeRateDto',
        :'address' => :'CryptoAddressDto',
        :'return_url' => :'String',
        :'redirect_url' => :'String',
        :'transactions' => :'Array<GatewayTransactionDto>',
        :'refund' => :'Object',
        :'refunds' => :'Array<Object>'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `OpenapiClient::SummaryPaymentDto` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `OpenapiClient::SummaryPaymentDto`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'uuid')
        self.uuid = attributes[:'uuid']
      end

      if attributes.key?(:'merchant_display_name')
        self.merchant_display_name = attributes[:'merchant_display_name']
      end

      if attributes.key?(:'merchant_id')
        self.merchant_id = attributes[:'merchant_id']
      end

      if attributes.key?(:'date_created')
        self.date_created = attributes[:'date_created']
      end

      if attributes.key?(:'expiry_date')
        self.expiry_date = attributes[:'expiry_date']
      end

      if attributes.key?(:'quote_expiry_date')
        self.quote_expiry_date = attributes[:'quote_expiry_date']
      end

      if attributes.key?(:'acceptance_expiry_date')
        self.acceptance_expiry_date = attributes[:'acceptance_expiry_date']
      end

      if attributes.key?(:'quote_status')
        self.quote_status = attributes[:'quote_status']
      end

      if attributes.key?(:'reference')
        self.reference = attributes[:'reference']
      end

      if attributes.key?(:'type')
        self.type = attributes[:'type']
      else
        self.type = 'IN'
      end

      if attributes.key?(:'sub_type')
        self.sub_type = attributes[:'sub_type']
      else
        self.sub_type = 'merchantPayIn'
      end

      if attributes.key?(:'status')
        self.status = attributes[:'status']
      end

      if attributes.key?(:'display_currency')
        self.display_currency = attributes[:'display_currency']
      end

      if attributes.key?(:'wallet_currency')
        self.wallet_currency = attributes[:'wallet_currency']
      end

      if attributes.key?(:'paid_currency')
        self.paid_currency = attributes[:'paid_currency']
      end

      if attributes.key?(:'fee_currency')
        self.fee_currency = attributes[:'fee_currency']
      end

      if attributes.key?(:'display_rate')
        self.display_rate = attributes[:'display_rate']
      end

      if attributes.key?(:'exchange_rate')
        self.exchange_rate = attributes[:'exchange_rate']
      end

      if attributes.key?(:'address')
        self.address = attributes[:'address']
      end

      if attributes.key?(:'return_url')
        self.return_url = attributes[:'return_url']
      end

      if attributes.key?(:'redirect_url')
        self.redirect_url = attributes[:'redirect_url']
      end

      if attributes.key?(:'transactions')
        if (value = attributes[:'transactions']).is_a?(Array)
          self.transactions = value
        end
      end

      if attributes.key?(:'refund')
        self.refund = attributes[:'refund']
      end

      if attributes.key?(:'refunds')
        if (value = attributes[:'refunds']).is_a?(Array)
          self.refunds = value
        end
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      sub_type_validator = EnumAttributeValidator.new('String', ["merchantPayIn", "merchantPayOut", "merchantRefund"])
      return false unless sub_type_validator.valid?(@sub_type)
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] sub_type Object to be assigned
    def sub_type=(sub_type)
      validator = EnumAttributeValidator.new('String', ["merchantPayIn", "merchantPayOut", "merchantRefund"])
      unless validator.valid?(sub_type)
        fail ArgumentError, "invalid value for \"sub_type\", must be one of #{validator.allowable_values}."
      end
      @sub_type = sub_type
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          uuid == o.uuid &&
          merchant_display_name == o.merchant_display_name &&
          merchant_id == o.merchant_id &&
          date_created == o.date_created &&
          expiry_date == o.expiry_date &&
          quote_expiry_date == o.quote_expiry_date &&
          acceptance_expiry_date == o.acceptance_expiry_date &&
          quote_status == o.quote_status &&
          reference == o.reference &&
          type == o.type &&
          sub_type == o.sub_type &&
          status == o.status &&
          display_currency == o.display_currency &&
          wallet_currency == o.wallet_currency &&
          paid_currency == o.paid_currency &&
          fee_currency == o.fee_currency &&
          display_rate == o.display_rate &&
          exchange_rate == o.exchange_rate &&
          address == o.address &&
          return_url == o.return_url &&
          redirect_url == o.redirect_url &&
          transactions == o.transactions &&
          refund == o.refund &&
          refunds == o.refunds
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [uuid, merchant_display_name, merchant_id, date_created, expiry_date, quote_expiry_date, acceptance_expiry_date, quote_status, reference, type, sub_type, status, display_currency, wallet_currency, paid_currency, fee_currency, display_rate, exchange_rate, address, return_url, redirect_url, transactions, refund, refunds].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      self.class.openapi_types.each_pair do |key, type|
        if attributes[self.class.attribute_map[key]].nil? && self.class.openapi_nullable.include?(key)
          self.send("#{key}=", nil)
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = OpenapiClient.const_get(type)
        klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
