=begin
#BVNK API Endpoints

#The BVNK API is designed to facilitate seamless and secure transactions including payments, channels, anddigital wallet transactions.

The version of the OpenAPI document: 1.0.1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::ChannelsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ChannelsApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::ChannelsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ChannelsApi' do
    it 'should create an instance of ChannelsApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::ChannelsApi)
    end
  end

  # unit tests for api_v2_channel_get
  # List Channels
  # Retrieves all channels related to a Merchant ID.
  # @param merchant_id The merchant ID that the channels belong to
  # @param [Hash] opts the optional parameters
  # @option opts [String] :offset Offset
  # @option opts [String] :max Maximum number of items in response
  # @option opts [PaymentStatusDto] :sort The attribute used to sort the data
  # @option opts [String] :order Ordering direction
  # @return [Array<MerchantChannel>]
  describe 'api_v2_channel_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for api_v2_channel_payment_get
  # List Channel Payments
  # Retrieves a list of payments to a channel on a specific Merchant ID.
  # @param merchant_id The Merchant ID
  # @param [Hash] opts the optional parameters
  # @option opts [String] :status 
  # @option opts [String] :from_date From which date to start searching.
  # @option opts [String] :to_date At which date to stop searching.
  # @option opts [String] :offset Where to start fetching records.
  # @option opts [String] :max Maximum number of items in response
  # @option opts [String] :order Ordering direction
  # @option opts [String] :q Can be UUID of the payment, reference, channel UUID, transaction hash, or wallet code.
  # @return [Array<MerchantChannelPayment>]
  describe 'api_v2_channel_payment_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for api_v2_channel_payment_uuid_get
  # Get Channel Payment
  # Retrieves a specific payment made into a channel.
  # @param uuid The UUID of the payment you are querying.
  # @param [Hash] opts the optional parameters
  # @return [MerchantChannelPayment]
  describe 'api_v2_channel_payment_uuid_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for api_v2_channel_post
  # Create Channel
  # Creates a channel that your end users can openly send payments to.
  # @param [Hash] opts the optional parameters
  # @option opts [MerchantChannelRequest] :merchant_channel_request 
  # @return [MerchantChannel]
  describe 'api_v2_channel_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for api_v2_channel_uuid_get
  # Get Channel
  # Retrieves a specific channel by UUID.
  # @param uuid The UUID of the channel you are querying
  # @param [Hash] opts the optional parameters
  # @return [MerchantChannel]
  describe 'api_v2_channel_uuid_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
