=begin
#BVNK API Endpoints

#The BVNK API is designed to facilitate seamless and secure transactions including payments, channels, anddigital wallet transactions.

The version of the OpenAPI document: 1.0.1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::CurrenciesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'CurrenciesApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::CurrenciesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CurrenciesApi' do
    it 'should create an instance of CurrenciesApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::CurrenciesApi)
    end
  end

  # unit tests for list_currencies_crypto
  # List Crypto Currencies
  # Retrieves a list of all cryptocurrencies available on the BVNK platform. This list represents cryptocurrencies that end users can select whilst making a payment.  For sandbox, only Ethereum (ETH) is fully functional.
  # @param [Hash] opts the optional parameters
  # @option opts [Float] :offset Offset
  # @option opts [Float] :max Maximum number of items in response
  # @option opts [Boolean] :allow_deposits list currencies that only allow deposits
  # @return [Array<Merchant>]
  describe 'list_currencies_crypto test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_currencies_deposit
  # List Wallet Currencies
  # These are the currencies that can be used to create a new wallet.
  # @param [Hash] opts the optional parameters
  # @option opts [Float] :offset Offset
  # @option opts [Float] :max Maximum number of items in response
  # @return [Array<Merchant>]
  describe 'list_currencies_deposit test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_currencies_fiat
  # List Fiat Currencies
  # Retrieves a list of all display fiat currencies available on BVNK&#39;s Crypto Payments API. This list refers to currencies merchants can display on a payment page to an end user. It does not represent the list of currencies that can be held on the platform in wallets.
  # @param [Hash] opts the optional parameters
  # @option opts [Float] :offset Offset
  # @option opts [Float] :max Maximum number of items in response
  # @option opts [Boolean] :usable list currencies that are usable
  # @return [Array<Merchant>]
  describe 'list_currencies_fiat test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
