=begin
#BVNK API Endpoints

#The BVNK API is designed to facilitate seamless and secure transactions including payments, channels, anddigital wallet transactions.

The version of the OpenAPI document: 1.0.1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::MerchantIDsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'MerchantIDsApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::MerchantIDsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of MerchantIDsApi' do
    it 'should create an instance of MerchantIDsApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::MerchantIDsApi)
    end
  end

  # unit tests for merchant_id_create
  # Create Merchant ID
  # Generate a Merchant ID for your account to process pay-ins and pay-outs through our API.  A Merchant ID is essential as it designates the account wallet where incoming pay-ins will be settled. For instance, if a Merchant ID is associated with a EUR wallet ID, any incoming USDT payment will be automatically converted to EUR and deposited in the designated EUR wallet.  Vice versa, any outgoing USDT payment will be automatically converted and withdrawn from the designated EUR wallet.  For further information, please visit https://docs.bvnk.com/docs/creating-your-first-merchant to learn more about creating your first Merchant ID.
  # @param [Hash] opts the optional parameters
  # @option opts [MerchantIdCreateRequest] :merchant_id_create_request 
  # @return [SummaryPaymentDto]
  describe 'merchant_id_create test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for merchant_id_list
  # List Merchant IDs
  # Retrieves merchant IDs setup on your account.
  # @param [Hash] opts the optional parameters
  # @return [Array<Merchant>]
  describe 'merchant_id_list test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
