=begin
#BVNK API Endpoints

#The BVNK API is designed to facilitate seamless and secure transactions including payments, channels, anddigital wallet transactions.

The version of the OpenAPI document: 1.0.1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::PaymentsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'PaymentsApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::PaymentsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PaymentsApi' do
    it 'should create an instance of PaymentsApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::PaymentsApi)
    end
  end

  # unit tests for api_v1_pay_summary_get
  # List Payments
  # Retrieves a list of payments on a specific Merchant ID
  # @param merchant_id Merchant identifier
  # @param [Hash] opts the optional parameters
  # @option opts [String] :customer_reference Customer reference
  # @option opts [String] :payment_external_id Merchant payment uuid
  # @option opts [String] :from_date Start date
  # @option opts [String] :to_date End date
  # @option opts [Float] :offset Offset
  # @option opts [Float] :max Maximum number of items in response
  # @option opts [PaymentStatusDto] :status 
  # @option opts [String] :order Ordering direction
  # @return [Array<SummaryPaymentDto>]
  describe 'api_v1_pay_summary_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for api_v1_pay_summary_post
  # Create payment
  # Creates a payment, either type IN or type OUT.
  # @param pay_request_dto 
  # @param [Hash] opts the optional parameters
  # @return [SummaryPaymentDto]
  describe 'api_v1_pay_summary_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for api_v1_pay_uuid_summary_get
  # Get Payment
  # Retrieves details of a specific payment using the UUID of the payment.
  # @param uuid merchant payment uuid
  # @param [Hash] opts the optional parameters
  # @return [SummaryPaymentDto]
  describe 'api_v1_pay_uuid_summary_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for api_v1_pay_validate_put
  # Validate Address
  # Validates that a crypto address is correct.  Use this endpoint to validate that an address exists, is correctly formatted, and includes all the required data. This endpoint can help prevent your end users losing funds when submitting a payout.
  # @param pay_out_detail_dto 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'api_v1_pay_validate_put test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
