=begin
#BVNK API Endpoints

#The BVNK API is designed to facilitate seamless and secure transactions including payments, channels, anddigital wallet transactions.

The version of the OpenAPI document: 1.0.1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::WalletsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'WalletsApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::WalletsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of WalletsApi' do
    it 'should create an instance of WalletsApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::WalletsApi)
    end
  end

  # unit tests for transaction_report
  # Transactions Report
  # Report all transactions from wallet in specified format. Report will be generated and sent to main account email in the specified format
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :wallet_id Date at to retrieve balances
  # @option opts [String] :from_date Export range from date in format &#39;yyyy-MM-dd&#39;
  # @option opts [String] :to_date Export range to date in format &#39;yyyy-MM-dd&#39;
  # @option opts [String] :format &#39;json&#39; - json format, &#39;csv&#39; - csv format
  # @option opts [String] :transaction_type Transaction type code
  # @return [Array<TransactionReport>]
  describe 'transaction_report test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for wallet_balance_list
  # List Wallet Balances
  # Retrieves the balances of your wallets on platform.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :date Date at to retrieve balances
  # @return [Array<Balance>]
  describe 'wallet_balance_list test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for wallet_create
  # Create Wallet
  # Creates a wallet on the BVNK platform.
  # @param [Hash] opts the optional parameters
  # @option opts [WalletRequest] :wallet_request 
  # @return [Wallet]
  describe 'wallet_create test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for wallet_list
  # List Wallets
  # Retrieves a list of wallets on your account.
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :offset start offset
  # @option opts [Integer] :max max number results
  # @return [Array<Wallet>]
  describe 'wallet_list test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for wallet_r_get
  # Get Wallet
  # Retrieves a specific wallet.
  # @param id start offset
  # @param [Hash] opts the optional parameters
  # @return [Wallet]
  describe 'wallet_r_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
